// src/routes/deck/[deckId]/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';
  import { getDeckStats, getCardsForDeck, resetDeckProgress } from '$lib/db/client';
  import type { DeckWithStats, CardWithReviewState } from '$lib/db/schema';

  let deck = $state<DeckWithStats | null>(null);
  let cards = $state<CardWithReviewState[]>([]);

  const deckId = $derived($page.params.deckId);

  onMount(async () => {
    await loadDeck();
  });

  async function loadDeck() {
    deck = getDeckStats(deckId);
    cards = getCardsForDeck(deckId);
  }

  const totalDue = $derived(deck ? deck.dueCount + deck.newCount : 0);

  async function handleReset() {
    resetDeckProgress(deckId);
    await loadDeck();
  }
</script>

<svelte:head><title>{deck?.name ?? 'Deck'} - Nihongo SRS</title></svelte:head>

{#if !deck}
  <div class="loading">Loading...</div>
{:else}
  <a href="/deck" class="back">← Back to Decks</a>

  <h1 class="title">{deck.name}</h1>
  <p class="desc">{deck.description}</p>

  <div class="stats-row">
    <div class="stat-card">
      <div class="stat-value" style="color: var(--color-primary)">{deck.masteryPercent}%</div>
      <div class="stat-label">Mastery</div>
    </div>
    <div class="stat-card">
      <div class="stat-value" style="color: var(--color-danger)">{deck.dueCount}</div>
      <div class="stat-label">Due</div>
    </div>
    <div class="stat-card">
      <div class="stat-value" style="color: var(--color-warning)">{deck.newCount}</div>
      <div class="stat-label">New</div>
    </div>
    <div class="stat-card">
      <div class="stat-value">{deck.cardCount}</div>
      <div class="stat-label">Total</div>
    </div>
  </div>

  {#if totalDue > 0}
    <button class="start-btn" onclick={() => goto(`/deck/review/${deckId}`)}>
      Start Review
      <span class="start-subtext">{totalDue} cards ready</span>
    </button>
  {:else}
    <div class="all-done">All caught up! Come back later. 🎉</div>
  {/if}

  <h2 class="section-title">Cards ({cards.length})</h2>
  <div class="card-list">
    {#each cards.slice(0, 50) as card}
      <div class="card-row">
        <span class="card-front">{card.front}</span>
        <span class="card-back">{card.back}</span>
        {#if card.reviewState}
          <span class="card-status">{card.reviewState.interval}d · EF {card.reviewState.easinessFactor.toFixed(1)}</span>
        {/if}
      </div>
    {/each}
  </div>
  {#if cards.length > 50}
    <p class="more-cards">+{cards.length - 50} more cards...</p>
  {/if}

  <button class="reset-btn" onclick={handleReset}>Reset deck progress</button>
{/if}

<style>
  .loading { text-align: center; padding: 4rem; color: var(--text-secondary); }
  .back { display: inline-block; margin-bottom: 1rem; color: var(--text-secondary); text-decoration: none; font-size: 0.875rem; }
  .title { font-size: 2rem; font-weight: 700; }
  .desc { color: var(--text-secondary); margin-bottom: 1.5rem; }
  .stats-row { display: flex; justify-content: space-around; margin-bottom: 1.5rem; }
  .stat-card { text-align: center; }
  .stat-value { font-size: 1.75rem; font-weight: 700; }
  .stat-label { font-size: 0.75rem; color: var(--text-secondary); }
  .start-btn {
    width: 100%; padding: 1rem; background: var(--color-primary); color: white;
    border: none; border-radius: 0.75rem; font-size: 1.125rem; font-weight: 700;
    display: flex; flex-direction: column; align-items: center; gap: 0.25rem;
    cursor: pointer; margin-bottom: 1.5rem; transition: opacity 0.15s;
  }
  .start-btn:active { opacity: 0.8; }
  .start-subtext { font-size: 0.875rem; font-weight: 400; opacity: 0.8; }
  .all-done { text-align: center; padding: 1.5rem; background: var(--surface); border-radius: 0.75rem; margin-bottom: 1.5rem; color: var(--text-secondary); }
  .section-title { font-size: 1.25rem; font-weight: 600; margin-bottom: 0.75rem; }
  .card-list { display: flex; flex-direction: column; gap: 0.5rem; }
  .card-row {
    display: flex; align-items: center; gap: 0.75rem; padding: 0.75rem;
    background: var(--card); border: 1px solid var(--card-border); border-radius: 0.5rem;
  }
  .card-front { font-size: 1.125rem; font-weight: 500; min-width: 60px; }
  .card-back { font-size: 0.875rem; flex: 1; color: var(--text-secondary); }
  .card-status { font-size: 0.7rem; color: var(--text-secondary); }
  .more-cards { text-align: center; padding: 0.5rem; color: var(--text-secondary); font-size: 0.875rem; }
  .reset-btn {
    width: 100%; padding: 0.75rem; background: transparent; color: var(--text-secondary);
    border: 1px solid var(--card-border); border-radius: 0.5rem; font-size: 0.875rem;
    cursor: pointer; margin-top: 1rem; transition: opacity 0.15s;
  }
  .reset-btn:active { opacity: 0.7; }
</style>

// src/app/deck/[deckId].tsx
import { useEffect, useState } from 'react';
import { useSQLiteContext } from 'expo-sqlite';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { ProgressRing } from '@/components/ProgressRing';
import { BottomTabInset, MaxContentWidth, Spacing } from '@/constants/theme';
import { useTheme } from '@/hooks/use-theme';
import { getDeckStats, getCardsForDeck, resetDeckProgress } from '@/db/client';
import type { DeckWithStats, CardWithReviewState } from '@/db/schema';

export default function DeckDetailScreen() {
  const db = useSQLiteContext();
  const router = useRouter();
  const { deckId } = useLocalSearchParams<{ deckId: string }>();
  const theme = useTheme();
  const insets = useSafeAreaInsets();
  const [deck, setDeck] = useState<DeckWithStats | null>(null);
  const [cards, setCards] = useState<CardWithReviewState[]>([]);

  useEffect(() => {
    (async () => {
      const stats = await getDeckStats(db, deckId);
      setDeck(stats);
      const allCards = await getCardsForDeck(db, deckId);
      setCards(allCards);
    })();
  }, [db, deckId]);

  if (!deck) {
    return (
      <View style={[styles.center, { backgroundColor: theme.background }]}>
        <ThemedText>Loading...</ThemedText>
      </View>
    );
  }

  const totalDue = deck.dueCount + deck.newCount;

  return (
    <ScrollView
      style={[styles.scrollView, { backgroundColor: theme.background }]}
      contentContainerStyle={[styles.contentContainer, { paddingTop: insets.top + Spacing.three, paddingBottom: insets.bottom + BottomTabInset + Spacing.three }]}>
      <View style={styles.content}>
        <ThemedText type="title" style={styles.title}>{deck.name}</ThemedText>
        <ThemedText themeColor="textSecondary" style={styles.description}>{deck.description}</ThemedText>

        <View style={styles.statsRow}>
          <View style={styles.statCard}>
            <ProgressRing progress={deck.masteryPercent / 100} size={72} />
            <ThemedText themeColor="textSecondary" style={styles.statLabel}>Mastery</ThemedText>
          </View>
          <View style={styles.statCard}>
            <ThemedText style={[styles.statValue, { color: theme.danger }]}>{deck.dueCount}</ThemedText>
            <ThemedText themeColor="textSecondary" style={styles.statLabel}>Due</ThemedText>
          </View>
          <View style={styles.statCard}>
            <ThemedText style={[styles.statValue, { color: theme.warning }]}>{deck.newCount}</ThemedText>
            <ThemedText themeColor="textSecondary" style={styles.statLabel}>New</ThemedText>
          </View>
          <View style={styles.statCard}>
            <ThemedText style={[styles.statValue, { color: theme.text }]}>{deck.cardCount}</ThemedText>
            <ThemedText themeColor="textSecondary" style={styles.statLabel}>Total</ThemedText>
          </View>
        </View>

        {totalDue > 0 && (
          <Pressable onPress={() => router.push(`/deck/review/${deckId}`)}>
            {({ pressed }) => (
              <ThemedView style={[styles.startButton, { backgroundColor: theme.primary }, pressed && styles.pressed]}>
                <ThemedText style={styles.startButtonText}>Start Review</ThemedText>
                <ThemedText style={styles.startButtonSubtext}>{totalDue} cards ready</ThemedText>
              </ThemedView>
            )}
          </Pressable>
        )}

        {totalDue === 0 && (
          <ThemedView type="backgroundElement" style={styles.allDone}>
            <ThemedText style={styles.allDoneText}>All caught up! Come back later.</ThemedText>
          </ThemedView>
        )}

        <View style={styles.cardBrowser}>
          <ThemedText type="subtitle" style={styles.sectionTitle}>Cards ({cards.length})</ThemedText>
          {cards.slice(0, 50).map((card) => (
            <ThemedView key={card.id} type="card" style={[styles.cardRow, { borderColor: theme.cardBorder }]}>
              <ThemedText style={styles.cardFront}>{card.front}</ThemedText>
              <ThemedText themeColor="textSecondary" style={styles.cardBack}>{card.back}</ThemedText>
              {card.reviewState && (
                <View style={styles.cardStatus}>
                  <ThemedText themeColor="textSecondary" style={styles.cardStatusText}>
                    {card.reviewState.interval}d · EF {card.reviewState.easinessFactor.toFixed(1)}
                  </ThemedText>
                </View>
              )}
            </ThemedView>
          ))}
          {cards.length > 50 && (
            <ThemedText themeColor="textSecondary" style={styles.moreCards}>
              +{cards.length - 50} more cards...
            </ThemedText>
          )}
        </View>

        <Pressable onPress={async () => {
          await resetDeckProgress(db, deckId);
          const stats = await getDeckStats(db, deckId);
          setDeck(stats);
          const allCards = await getCardsForDeck(db, deckId);
          setCards(allCards);
        }}>
          {({ pressed }) => (
            <ThemedView type="backgroundElement" style={[styles.resetButton, pressed && styles.pressed]}>
              <ThemedText themeColor="textSecondary" style={styles.resetText}>Reset deck progress</ThemedText>
            </ThemedView>
          )}
        </Pressable>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  scrollView: {
    flex: 1,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contentContainer: {
    alignItems: 'center',
  },
  content: {
    width: '100%',
    maxWidth: MaxContentWidth,
    paddingHorizontal: Spacing.four,
    gap: Spacing.three,
  },
  title: {
    fontSize: 32,
    fontWeight: '700' as const,
  },
  description: {
    fontSize: 16,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    gap: Spacing.two,
  },
  statCard: {
    alignItems: 'center',
    gap: Spacing.one,
  },
  statValue: {
    fontSize: 28,
    fontWeight: '700' as const,
  },
  statLabel: {
    fontSize: 12,
  },
  startButton: {
    borderRadius: Spacing.three,
    paddingVertical: Spacing.four,
    paddingHorizontal: Spacing.five,
    alignItems: 'center',
    gap: Spacing.one,
    width: '100%',
  },
  startButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700' as const,
  },
  startButtonSubtext: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 14,
  },
  pressed: {
    opacity: 0.8,
  },
  allDone: {
    borderRadius: Spacing.three,
    paddingVertical: Spacing.four,
    paddingHorizontal: Spacing.five,
    alignItems: 'center',
    width: '100%',
  },
  allDoneText: {
    fontSize: 16,
  },
  cardBrowser: {
    gap: Spacing.two,
    width: '100%',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600' as const,
  },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.three,
    borderRadius: Spacing.two,
    borderWidth: 1,
    gap: Spacing.three,
  },
  cardFront: {
    fontSize: 20,
    fontWeight: '500' as const,
    minWidth: 60,
  },
  cardBack: {
    fontSize: 14,
    flex: 1,
  },
  cardStatus: {
    alignItems: 'flex-end',
  },
  cardStatusText: {
    fontSize: 11,
  },
  moreCards: {
    fontSize: 14,
    textAlign: 'center',
    paddingVertical: Spacing.two,
  },
  resetButton: {
    borderRadius: Spacing.three,
    paddingVertical: Spacing.three,
    paddingHorizontal: Spacing.four,
    alignItems: 'center',
    width: '100%',
  },
  resetText: {
    fontSize: 14,
  },
});
